baseurl = "https://yzlnew.com/"
languageCode = "zh-CN"
title = "Yellow Stone"
theme = "ink"
paginate = 5

copyright = "© Copyright @yzlnew"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsuseclasses = true

googleAnalytics = "UA-61197619-1"

summaryLength = 20

[params]
    subtitle = ""
    featherIconsCDN = true
    mode = "light" # "dark", "auto", "light"
# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
# customJS = ["https://code.jquery.com/jquery-3.4.1.js", "js/custom1.js"]  # Custom JS scripts.
    avatar = "img/penrose.webp"
    favicon = "img/favicon.ico"

    cachebuster = true
    dateform = "Jan 2, 2006"
    dateformfull = "Mon Jan 2 2006 15:04:05 MST"
    description = ""
    extracssfiles = ["/css/webfont.css","/css/override.css"]
    i18n_flags = true
    lang = "cn"

    gitalk                 = true
# if gitalk is true, the following params should be set. These parameters could be retrieved from github OAuth
    gitalk_clientID        = "4ccff83836edce535e3c"
    gitalk_clientSecret    = "daeca7033b9770d0f062e007477bc4d116499434"
    gitalk_repo            = "yzlnew.github.io"
    gitalk_owner           = "yzlnew"
    gitalk_admin           = ['yzlnew']

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 2

[[menu.main]]
name = "Life"
url = "/life"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

[[params.social]]
name = "Mail"
icon = "mail"
url = "yzlnew@gmail.com"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/yzlnew"

[[params.social]]
name = "Telegram"
icon = "message-square"
url = "https://t.me/r0brew"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"


[taxonomies]
   tag = "tags"


defaultContentLanguage = "cn" # 页面中文
author = "@yzlnew"
builddrafts = false
canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

[permalinks]
blog = ":year/:month/:filename"
