baseurl = "https://yzlnew.com/"
languageCode = "zh-CN"
hasCJKLanguage = true
title = "yzl çš„æ—¶ç©ºå›ç¯"
theme = "ink"
paginate = 8

copyright = "Â© Copyright Ye Zhiling"
googleAnalytics = "UA-61197619-1"

summaryLength = 20

[params]
    subtitle = "Let me fly to the ğŸŒ™"
    featherIconsCDN = true
    mode = "auto" # "dark", "auto", "light"
    customCSS = "css/custom.css"  # Custom CSS applied to default styles.
    customDarkCSS = "css/custom_dark.css"  # Custom styles applied to dark mode css.
    avatar = "img/avatar.png"
    favicon = "img/favicon.png"

    i18n_flags = true
    lang = "cn"

    gitalk                 = true
# if gitalk is true, the following params should be set. These parameters could be retrieved from github OAuth
    gitalk_clientID        = "4ccff83836edce535e3c"
    gitalk_clientSecret    = "daeca7033b9770d0f062e007477bc4d116499434"
    gitalk_repo            = "yzlnew.github.io"
    gitalk_owner           = "yzlnew"
    gitalk_admin           = ['yzlnew']

[[menu.main]]
name = "ä¸»é¡µ"
url = "/"
weight = 1

[[menu.main]]
name = "å…³äºæˆ‘"
url = "/about"
weight = 4

[[menu.main]]
name = "æ ‡ç­¾"
url = "/tags"
weight = 5

[[params.social]]
name = "Mail"
icon = "mail"
url = "mailto:yzlnew@gmail.com"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/yzlnew"

[[params.social]]
name = "Telegram"
icon = "message-square"
url = "https://t.me/r0brew"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"


[taxonomies]
   tag = "tags"


defaultContentLanguage = "cn" # é¡µé¢ä¸­æ–‡
author = "@yzlnew"
builddrafts = false
canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

[permalinks]
blog = ":year/:month/:filename"

[markup]
  [markup.tableOfContents]
    endLevel = 4
    startLevel = 3
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    style = "pastie"
    tabWidth = 2
